blank_issues_enabled: false
contact_links:
  - name: buttercup-to-keepass documentation
    url: https://github.com/adaltas/buttercup-to-keepass
    about: Check out the documentation for answers to common questions.
